# Generated by Django 5.2.4 on 2025-08-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_task_create'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_complete', models.OrderBy(models.F('deadline'), nulls_last=True)]},
        ),
    ]
