# Generated by Django 5.2.4 on 2025-09-05 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_friendrequest_receiver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('user_1', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='friendship_user_1', to=settings.AUTH_USER_MODEL)),
                ('user_2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='friendship_user_2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
