# Generated by Django 5.2.4 on 2025-09-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_flashcardsfolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardsfolder',
            name='flashcards_number',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
